// Showcased projects. Screenshots live in public/shots (captured with scripts/shoot.mjs).
const shot = (name, caption) => ({ src: `shots/${name}.webp`, caption });

export const projects = [
  {
    id: 'learnova',
    name: 'Learnova',
    tagline: 'AI learning workspace that turns course PDFs into a study plan.',
    year: '2025',
    role: 'Full-stack & ML engineer',
    kind: 'AI · EdTech',
    summary:
      'Students upload their course PDFs; Learnova reads them with OCR and LLMs, then generates flashcards, chapter summaries, adaptive exams and a knowledge graph of the concepts. Exams are graded with partial credit, and a knowledge-gap analysis tells each student exactly which concept to revisit.',
    highlights: [
      'Adaptive exams with partial-credit grading and per-concept performance',
      'Knowledge-gap analysis that explains why an answer missed full credit',
      'Concept map built from the documents (knowledge graph)',
      'Admin console: LLM usage monitoring, token costs and grading-model tuning',
      'Semantic library search with pgvector embeddings',
    ],
    stack: ['Next.js 16', 'TypeScript', 'Tailwind', 'FastAPI', 'PostgreSQL', 'pgvector', 'SQLAlchemy', 'LLMs', 'OCR'],
    metrics: [
      ['6', 'AI study tools'],
      ['Async', 'FastAPI + asyncpg'],
      ['Local or cloud', 'Ollama / OpenAI'],
    ],
    links: [['GitHub', 'https://github.com/lebron79/Learnova']],
    shots: [
      shot('learnova-exam-results', 'Exam results with per-concept performance'),
      shot('learnova-gap', 'Knowledge-gap analysis'),
      shot('learnova-flashcards', 'Generated flashcards'),
      shot('learnova-concepts', 'Concept map / knowledge graph'),
      shot('learnova-admin', 'Admin console: grading model'),
      shot('learnova-documents', 'Course library and repositories'),
      shot('learnova-landing', 'Landing page'),
    ],
  },
  {
    id: 'tunitech',
    name: 'TuniTech Advisor',
    tagline: 'Smartphone market intelligence and price prediction for Tunisia.',
    year: '2025',
    role: 'Data & full-stack (team project)',
    kind: 'ML · Market data',
    summary:
      'Scrapes 1,236 smartphones from five Tunisian retailers, cleans and merges them, and serves a machine-learning price predictor alongside recommendations, comparisons and a live market dashboard. Deployed end to end with Docker on Render, Vercel and MongoDB Atlas, with experiments tracked in MLflow.',
    highlights: [
      'Multi-store scraping pipeline with a weekly scheduler',
      'KNN price model: R² = 0.9998, MAE ≈ 4–33 TND',
      'Recommendations by budget, specs and use case',
      'Market dashboard: price segments, OS share, store comparison',
      'JWT auth, reviews, trending and 90-day price history',
    ],
    stack: ['Python', 'scikit-learn', 'MLflow', 'FastAPI', 'React', 'TypeScript', 'MongoDB', 'Docker', 'BeautifulSoup'],
    metrics: [
      ['1,236', 'phones indexed'],
      ['5', 'retailers scraped'],
      ['0.9998', 'R² price model'],
    ],
    links: [
      ['Live app', 'https://tuni-tech-advisor.vercel.app'],
      ['GitHub', 'https://github.com/iheblam/TuniTech-Advisor'],
    ],
    shots: [
      shot('tuni-market', 'Market dashboard'),
      shot('tuni-home', 'Home'),
      shot('tuni-predict', 'AI price predictor'),
      shot('tuni-recommend', 'Recommendations'),
      shot('tuni-brands', 'Brand analytics'),
      shot('tuni-search', 'Cross-store search'),
    ],
  },
  {
    id: 'speedy',
    name: 'Speedy',
    tagline: 'Open-source, IDM-style download manager with adaptive multi-connection downloads.',
    year: '2026',
    role: 'Solo: design & engineering',
    kind: 'Desktop · Networking',
    summary:
      'A desktop download manager written in Python and Qt. It starts with one connection and adds one per second while every connection keeps flowing, stopping as soon as the server starts throttling. The remaining work is re-split between connections as they join or finish, stalled connections are retired, and progress is saved every 2 s, so downloads resume after a crash or a reboot. A browser extension hands over downloads (cookies included) and adds a "Download this video" button on YouTube and about 1,800 other sites.',
    highlights: [
      'Adaptive connections: ramps up to 8 and backs off when the server throttles',
      'Dynamic segmentation: the largest remaining chunk is split only when it is worth a new request',
      'Crash-proof pause/resume with ETag checks against changed files',
      'Queue, global speed limiter, retries with exponential backoff',
      'Chrome/Edge MV3 extension + local bridge that only accepts extension requests',
      'Video pages: yt-dlp stream discovery, parallel audio/video download, lossless ffmpeg merge',
    ],
    stack: ['Python', 'PySide6 / Qt', 'requests', 'HTTP Range', 'yt-dlp', 'ffmpeg', 'Chrome MV3', 'unittest'],
    metrics: [
      ['8', 'adaptive connections'],
      ['2 s', 'resume checkpoints'],
      ['~1,800', 'video sites'],
    ],
    links: [],
    shots: [
      shot('speedy-overview', 'Downloads with the live progress window'),
      shot('speedy-main', 'Main window: queue, filters, live speed graph'),
      shot('speedy-progress', 'Progress window: connections map and speed'),
      shot('speedy-connections', '8 parallel connections on a 600 MB file'),
      shot('speedy-complete', 'Download complete'),
    ],
  },
  {
    id: 'rakcha',
    name: 'Rakcha',
    tagline: 'Private, offline-first course library with an encrypted vault.',
    year: '2026',
    role: 'Solo: design & engineering',
    kind: 'Product · Security',
    summary:
      'A desktop-class course library that runs entirely on the laptop: subjects, sections, PDFs and notes, a password vault encrypted with AES-GCM, and a Gmail reader that scores incoming mail against the timetable to file course material automatically. Phones get a full offline copy over the local Wi-Fi: mDNS discovery, a self-issued certificate authority and a one-time pairing code.',
    highlights: [
      'One process: Fastify and SQLite (node:sqlite), no native dependencies',
      'Vault sealed with scrypt + AES-GCM; Windows Hello unlock',
      'Course-mail classifier: weighted scoring on sender, subject and attachments',
      'LAN phone sync with its own CA, mDNS and an offline PWA',
      'Hand-built UI: three themes, canvas aurora, reduced-motion aware',
    ],
    stack: ['Node.js', 'Fastify', 'SQLite', 'React 19', 'Vite', 'node:crypto', 'IMAP', 'PWA', 'pdf.js'],
    metrics: [
      ['0', 'cloud services'],
      ['AES-GCM', 'encrypted vault'],
      ['1 click', 'to launch'],
    ],
    links: [],
    shots: [
      shot('rakcha-home', 'Dashboard'),
      shot('rakcha-files', 'All files, across every subject'),
      shot('rakcha-library', 'Library'),
      shot('rakcha-subject', 'Subject with sections'),
      shot('rakcha-notes', 'Notes'),
      shot('rakcha-lock', 'Vault lock screen'),
    ],
  },
  {
    id: 'lidara',
    name: 'Lidara',
    tagline: 'Gmail inbox organizer: review first, then apply.',
    year: '2026',
    role: 'Solo: design & engineering',
    kind: 'Automation · Productivity',
    summary:
      'Lidara reads the inbox through the Gmail API, groups mail by sender and proposes labels (Academic, Professional, Dev Tools, Ads) from configurable domain rules and ad detection. Nothing changes until you approve: you review sender by sender, override categories, then apply in one batch. Ads are archived, never deleted.',
    highlights: [
      'Rule engine: domain patterns, newsletter and promotions detection',
      'Sender-level review workflow with per-sender overrides',
      'Batched Gmail API writes; decisions persisted locally',
      'Safe by design: archive, never delete; fully reversible',
    ],
    stack: ['Python', 'Flask', 'Gmail API', 'OAuth 2.0', 'YAML rules', 'Vanilla JS'],
    metrics: [
      ['500', 'mails per pass'],
      ['5', 'smart labels'],
      ['0', 'mails deleted'],
    ],
    links: [],
    shots: [
      shot('lidara-all', 'Inbox grouped by sender (demo data)'),
      shot('lidara-academic', 'Academic label, expanded (demo data)'),
      shot('lidara-ads', 'Ads detection (demo data)'),
    ],
  },
];
